---
meta:
  kit:             jumpbox
  release:         Jumpbox Genesis Kit
  target:          pipes/genesis
  url:             https://pipes.scalecf.net
  iaas:            vsphere
  exposed:         false
  version_file:    version
  initial_version: 1.3.4-rc.2

  upstream:
    categories:
    - name:  core
      label: Jumpbox Core Components
      default: true

    bosh_releases:
    - name:       jumpbox
      type:       github-release
      repository: cloudfoundry-community/jumpbox-boshrelease

    - name:       networking
      type:       bosh-io-release
      repository: cloudfoundry/networking-release

    - name:       openvpn
      type:       github-release
      repository: cloudfoundry-community/openvpn-bosh-release

    - name:       toolbelt
      type:       github-release
      repository: cloudfoundry-community/toolbelt-boshrelease

  bosh:
    uri:      ((bosh.uri))
    username: ((bosh.username))
    password: ((bosh.password))
    cacert:   ((bosh.ca))

  vault:
    url:       ((vault.url))
    token:     ((vault.token))

  aws:
    access_key: ((cloudfoundry-community-aws.access_key_id))
    secret_key: ((cloudfoundry-community-aws.secret_access_key))

  github:
    owner:        genesis-community
    repo:         jumpbox-genesis-kit
    branch:       develop
    main-branch:  main
    private_key:  ((github.private_key))
    access_token: ((github.access_token))
    name:         ((github.name))
    email:        ((github.email))

  shout:
    url:      ((shout.url))
    username: ((shout.username))
    password: ((shout.password))